/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WelcomeRouteImport } from './routes/welcome'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardWorkspacesRouteImport } from './routes/dashboard/workspaces'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardAsrRouteImport } from './routes/dashboard/asr'
import { Route as DashboardVideosIndexRouteImport } from './routes/dashboard/videos/index'
import { Route as DashboardPluginsIndexRouteImport } from './routes/dashboard/plugins/index'
import { Route as DashboardVideosVideoIdRouteImport } from './routes/dashboard/videos/$videoId'
import { Route as DashboardPluginsPluginIdRouteImport } from './routes/dashboard/plugins/$pluginId'
import { Route as DashboardVideosStreamerStreamerIdRouteImport } from './routes/dashboard/videos/streamer/$streamerId'

const WelcomeRoute = WelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardWorkspacesRoute = DashboardWorkspacesRouteImport.update({
  id: '/workspaces',
  path: '/workspaces',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAsrRoute = DashboardAsrRouteImport.update({
  id: '/asr',
  path: '/asr',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVideosIndexRoute = DashboardVideosIndexRouteImport.update({
  id: '/videos/',
  path: '/videos/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPluginsIndexRoute = DashboardPluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardVideosVideoIdRoute = DashboardVideosVideoIdRouteImport.update({
  id: '/videos/$videoId',
  path: '/videos/$videoId',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPluginsPluginIdRoute =
  DashboardPluginsPluginIdRouteImport.update({
    id: '/plugins/$pluginId',
    path: '/plugins/$pluginId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardVideosStreamerStreamerIdRoute =
  DashboardVideosStreamerStreamerIdRouteImport.update({
    id: '/videos/streamer/$streamerId',
    path: '/videos/streamer/$streamerId',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/dashboard/asr': typeof DashboardAsrRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/plugins/$pluginId': typeof DashboardPluginsPluginIdRoute
  '/dashboard/videos/$videoId': typeof DashboardVideosVideoIdRoute
  '/dashboard/plugins/': typeof DashboardPluginsIndexRoute
  '/dashboard/videos/': typeof DashboardVideosIndexRoute
  '/dashboard/videos/streamer/$streamerId': typeof DashboardVideosStreamerStreamerIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/welcome': typeof WelcomeRoute
  '/dashboard/asr': typeof DashboardAsrRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/plugins/$pluginId': typeof DashboardPluginsPluginIdRoute
  '/dashboard/videos/$videoId': typeof DashboardVideosVideoIdRoute
  '/dashboard/plugins': typeof DashboardPluginsIndexRoute
  '/dashboard/videos': typeof DashboardVideosIndexRoute
  '/dashboard/videos/streamer/$streamerId': typeof DashboardVideosStreamerStreamerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/welcome': typeof WelcomeRoute
  '/dashboard/asr': typeof DashboardAsrRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
  '/dashboard/workspaces': typeof DashboardWorkspacesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/plugins/$pluginId': typeof DashboardPluginsPluginIdRoute
  '/dashboard/videos/$videoId': typeof DashboardVideosVideoIdRoute
  '/dashboard/plugins/': typeof DashboardPluginsIndexRoute
  '/dashboard/videos/': typeof DashboardVideosIndexRoute
  '/dashboard/videos/streamer/$streamerId': typeof DashboardVideosStreamerStreamerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/welcome'
    | '/dashboard/asr'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/workspaces'
    | '/dashboard/'
    | '/dashboard/plugins/$pluginId'
    | '/dashboard/videos/$videoId'
    | '/dashboard/plugins/'
    | '/dashboard/videos/'
    | '/dashboard/videos/streamer/$streamerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/welcome'
    | '/dashboard/asr'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/workspaces'
    | '/dashboard'
    | '/dashboard/plugins/$pluginId'
    | '/dashboard/videos/$videoId'
    | '/dashboard/plugins'
    | '/dashboard/videos'
    | '/dashboard/videos/streamer/$streamerId'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/welcome'
    | '/dashboard/asr'
    | '/dashboard/settings'
    | '/dashboard/tasks'
    | '/dashboard/workspaces'
    | '/dashboard/'
    | '/dashboard/plugins/$pluginId'
    | '/dashboard/videos/$videoId'
    | '/dashboard/plugins/'
    | '/dashboard/videos/'
    | '/dashboard/videos/streamer/$streamerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  WelcomeRoute: typeof WelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/welcome': {
      id: '/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof WelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/workspaces': {
      id: '/dashboard/workspaces'
      path: '/workspaces'
      fullPath: '/dashboard/workspaces'
      preLoaderRoute: typeof DashboardWorkspacesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/asr': {
      id: '/dashboard/asr'
      path: '/asr'
      fullPath: '/dashboard/asr'
      preLoaderRoute: typeof DashboardAsrRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/videos/': {
      id: '/dashboard/videos/'
      path: '/videos'
      fullPath: '/dashboard/videos/'
      preLoaderRoute: typeof DashboardVideosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plugins/': {
      id: '/dashboard/plugins/'
      path: '/plugins'
      fullPath: '/dashboard/plugins/'
      preLoaderRoute: typeof DashboardPluginsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/videos/$videoId': {
      id: '/dashboard/videos/$videoId'
      path: '/videos/$videoId'
      fullPath: '/dashboard/videos/$videoId'
      preLoaderRoute: typeof DashboardVideosVideoIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/plugins/$pluginId': {
      id: '/dashboard/plugins/$pluginId'
      path: '/plugins/$pluginId'
      fullPath: '/dashboard/plugins/$pluginId'
      preLoaderRoute: typeof DashboardPluginsPluginIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/videos/streamer/$streamerId': {
      id: '/dashboard/videos/streamer/$streamerId'
      path: '/videos/streamer/$streamerId'
      fullPath: '/dashboard/videos/streamer/$streamerId'
      preLoaderRoute: typeof DashboardVideosStreamerStreamerIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAsrRoute: typeof DashboardAsrRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
  DashboardWorkspacesRoute: typeof DashboardWorkspacesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPluginsPluginIdRoute: typeof DashboardPluginsPluginIdRoute
  DashboardVideosVideoIdRoute: typeof DashboardVideosVideoIdRoute
  DashboardPluginsIndexRoute: typeof DashboardPluginsIndexRoute
  DashboardVideosIndexRoute: typeof DashboardVideosIndexRoute
  DashboardVideosStreamerStreamerIdRoute: typeof DashboardVideosStreamerStreamerIdRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAsrRoute: DashboardAsrRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTasksRoute: DashboardTasksRoute,
  DashboardWorkspacesRoute: DashboardWorkspacesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPluginsPluginIdRoute: DashboardPluginsPluginIdRoute,
  DashboardVideosVideoIdRoute: DashboardVideosVideoIdRoute,
  DashboardPluginsIndexRoute: DashboardPluginsIndexRoute,
  DashboardVideosIndexRoute: DashboardVideosIndexRoute,
  DashboardVideosStreamerStreamerIdRoute:
    DashboardVideosStreamerStreamerIdRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  WelcomeRoute: WelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
